# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ElectricVehicleRoutingGui
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"." \
    -l$(SolutionDir)ElectricVehicleRoutingCore/lib/ElectricVehicleRoutingCore
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(ElectricVehicleRoutingGui.pri)
